hl.on("hyprland.start", function()
	hl.exec_cmd("awww-daemon")
	-- hl.exec_cmd("hypridle")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("dbus-update-activation-environment --all")
	hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("qs")
	hl.exec_cmd("nm-applet --indicator")
	hl.exec_cmd("/opt/activitywatch/aw-server/aw-server")
	hl.exec_cmd("sleep 2 && aw-awatcher")
end)
