hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "catppuccin-mocha-dark-cursors")
hl.env("HYPRCURSOR_THEME", "Catppuccin Mocha Dark")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
