foreground              #e8eaec
background              #141619
selection_foreground    #141619
selection_background    #cc6569
cursor                  #e8eaec
cursor_text_color       #141619
url_color               #cc6569
active_border_color     #cc6569
inactive_border_color   #888888
bell_border_color       #cc6569
active_tab_foreground   #141619
active_tab_background   #cc6569
inactive_tab_foreground #e8eaec
inactive_tab_background #141619
tab_bar_background      #141619
color0  #888888
color8  #888888
color1  #cc6569
color9  #cc6569
color2  #cc6569
color10 #cc6569
color3  #cc6569
color11 #cc6569
color4  #cc6569
color12 #cc6569
color5  #cc6569
color13 #cc6569
color6  #cc6569
color14 #cc6569
color7  #e8eaec
color15 #e8eaec
color16 #1e2023
